name: Automated Preprocessing Pipeline

#Trigger
on:
  push:
    branches:
      - main
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  preprocess-data:
    runs-on: ubuntu-latest
    
    steps:
    #Checkout repository 
    - name: Checkout code
      uses: actions/checkout@v3
      
    #Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
        
    #Install dependencies
    - name: Install libraries
      run: |
        pip install -r requirements.txt
        
    #Run Preprocessing Script
    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_yosuatriantara.py
        
    #Commit dan Push dataset terbaru ke repo
    - name: Commit and Push processed data
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add preprocessing/online_retail_customer_churn_preprocessing.csv
        git commit -m "Auto-update processed dataset by GitHub Actions" || echo "No changes to commit"
        git push